bboard/urls.py
from django.urls import path, re_path, include
from rest_framework.routers import DefaultRouter

from bboard.models import Bb
from bboard.views import (index, by_rubric, BbCreateView, add_and_save, detail,
                          BbByRubricView, BbDetailView, BbAddView, BbEditView,
                          BbDeleteView, BbIndexView, BbRedirectView, edit,
                          rubrics, search, api_rubrics, api_rubric_detail, APIRubrics, APIRubricDetail,
                          APIRubricViewSet)  # add, add_save

app_name = 'bboard'

router = DefaultRouter()
router.register('rubrics', APIRubricViewSet)


urlpatterns = [
    # path('api/rubrics/<int:pk>/', api_rubric_detail),
    # path('api/rubrics/', api_rubrics),

    # path('api/rubrics/<int:pk>/', APIRubricDetail.as_view),
#     path('api/rubrics/', APIRubrics.as_view()),

    path('api/', include(router.urls)), # api/rubrics/ GET и POST

    path('api/drf-auth', include('rest_framework.urls')),

    path('rubrics/', rubrics, name='rubrics'),

    # path('bboard/', сюда\класс, name='rubrics'),

    path('add/', BbCreateView.as_view(), name='add'),

    # path('update/<int:pk>/', BbEditView.as_view(), name='update'),
    path('update/<int:pk>/', edit, name='update'),

    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),
    path('<int:rubric_id>/', BbByRubricView.as_view(), name='by_rubric'),

    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),
    # path('detail/<int:year>/<int:month>/<int:day>/<int:pk>/',
    #      BbDetailView.as_view(), name='detail'),
    path('detail/<int:year>/<int:month>/<int:day>/<int:pk>/',
         BbRedirectView.as_view(), name='old_detail'),

    path('', index, name='index'),
    # path('', BbIndexView.as_view(), name='index'),

    path('search/', search, name='search'),
]

samplesite/urls.py
from tempfile import template

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/login/', LoginView.as_view(), name='login'),
    # path('accounts/logout/',
    #      LogoutView.as_view(next_page='bboard:index'), name='logout'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),

    path('accounts/password_change/',
         PasswordChangeView.as_view(
             template_name='registration/change_password.html'),
         name='password_change'),
    path('accounts/password_change/done/',
         PasswordChangeDoneView.as_view(
             template_name='registration/password_changed.html'),
         name='password_change_done'),

    path('testapp/', include('testapp.urls', namespace='testapp')),
    path('', include('bboard.urls', namespace='bboard')),
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.THUMBNAIL_MEDIA_URL,
#                       document_root=settings.THUMBNAIL_MEDIA_URL)

bboard/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.db import transaction
from django.db.models import Count
from django.forms import modelformset_factory
from django.http import HttpResponse, HttpResponseRedirect, HttpResponsePermanentRedirect, HttpResponseNotFound, \
    Http404, StreamingHttpResponse, FileResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.template import loader
from django.template.loader import get_template, render_to_string
from django.urls import reverse_lazy, reverse
from django.views.decorators.http import require_http_methods
from django.views.generic.dates import ArchiveIndexView, DateDetailView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView, RedirectView
from django.views.generic.edit import CreateView, FormView, UpdateView, DeleteView
from django.forms.formsets import ORDERING_FIELD_NAME
from precise_bbcode.bbcode import get_parser
from rest_framework import status, generics
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet

from bboard.forms import BbForm, RubricFormSet, SearchForm
from bboard.models import Bb, Rubric
from bboard.serializers import RubricSerializer # BbSerializer



def index(request):
    bbs = Bb.objects.order_by('-published')
    # rubrics = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
    # rubrics = Rubric.objects.all()
    # rubrics = Rubric.objects.order_by_bb_count()
    # rubrics = Rubric.objects.all().order_by_bb_count()
    # rubrics = Rubric.bbs.all()

    paginator = Paginator(bbs, 2)

    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1

    page = paginator.get_page(page_num)

    # context = {'bbs': bbs, 'rubrics': rubrics}
    # context = {'rubrics': rubrics, 'bbs': page.object_list, 'page': page}
    context = {'bbs': page.object_list, 'page': page}

    return render(request, 'bboard/index.html', context)


class BbIndexView(ArchiveIndexView):
    model = Bb
    date_field = 'published'
    date_list_period = 'year'
    template_name = 'bboard/index.html'
    context_object_name = 'bbs'
    allow_empty = True
    # allow_future = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
        return context


def by_rubric(request, rubric_id):
    rubrics = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
    current_rubric = Rubric.objects.get(pk=rubric_id)
    bbs = get_list_or_404(Bb, rubric=rubric_id)

    context = {'bbs': bbs, 'rubrics': rubrics, 'current_rubric': current_rubric}

    return render(request, 'bboard/by_rubric.html', context)


class BbByRubricView(ListView):
    template_name = 'bboard/by_rubric.html'
    context_object_name = 'bbs'

    def get_queryset(self):
        # return Bb.objects.filter(rubric=self.kwargs['rubric_id'])
        rubric = Rubric.objects.get(pk=self.kwargs['rubric_id'])
        # return rubric.bb_set.all()
        return rubric.bb_set(manager='by_price').all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
        context['current_rubric'] = Rubric.objects.get(pk=self.kwargs['rubric_id'])
        return context


class BbCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'bboard/create.html'
    form_class = BbForm
    # success_url = reverse_lazy('bboard:index')
    success_url = '/{rubric_id}'
    success_message = 'Объявление о продаже товаров "%(title)s " созданно'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
        return context


class BbEditView(UpdateView):
    model = Bb
    form_class = BbForm
    success_url = '/{rubric_id}'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
        return context

def commit_handler():
    print('Транзакция закоммичена')

# @transaction.non_atomic_requests
# @transaction.atomic
def edit(request, pk):
    bb = Bb.objects.get(pk=pk)

    if request.method == 'POST':
        bbf = BbForm(request.POST, request.FILES,instance=bb)
        if bbf.is_valid():
            if bbf.has_changed():
                bbf.save()
                messages.add_message(request, messages.SUCCESS, 'Объявление исправленно!',
                                     extra_tags='alert alert-success')
                messages.success(request, 'Обьявление исправленно - 2',
                                 extra_tags='alert alert-success')
            return HttpResponseRedirect(
                reverse('bboard:by_rubric',
                        kwargs={'rubric_id': bbf.cleaned_data['rubric'].pk}))
        else:
            context = {'form': bbf}
            return render(request, 'bboard/bb_form.html', context)
    else:
        bbf = BbForm(instance=bb)
        context = {'form': bbf}
        return render(request, 'bboard/bb_form.html', context)


class BbAddView(FormView):
    template_name = 'bboard/create.html'
    form_class = BbForm
    initial = {'price': 0.0}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
        return context

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_form(self, form_class=None):
        self.object = super().get_form(form_class)
        return self.object

    def get_success_url(self):
        return reverse('bboard:by_rubric',
                       kwargs={'rubric_id': self.object.cleaned_data['rubric'].pk})


@require_http_methods(['GET', 'POST'])
def add_and_save(request):
    if request.method == 'POST':
        bbf = BbForm(request.POST)

        if bbf.is_valid():
            bbf.save()
            # return HttpResponseRedirect(reverse('bboard:by_rubric',
            #     kwargs={'rubric_id': bbf.cleaned_data['rubric'].pk}))
            return redirect('bboard:by_rubric',
                            rubric_id=bbf.cleaned_data['rubric'].pk)
        else:
            context = {'form': bbf}
            return render(request, 'bboard/create.html', context)
    else:
        bbf = BbForm()
        context = {'form': bbf}
        return render(request, 'bboard/create.html', context)


def detail(request, bb_id):
    bb = get_object_or_404(Bb, pk=bb_id)

    parser = get_parser()
    bb = Bb.objects.get(Bb, pk=bb_id)
    parsed_content = parser.render(bb.content)

    rubrics = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
    context = {'bb': bb, 'rubrics': rubrics, 'parsed_content': parsed_content}

    return render(request, 'bboard/detail.html', context)


class BbDetailView(DetailView):
    model = Bb

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
        return context


# class BbDetailView(DateDetailView):
#     model = Bb
#     date_field = 'published'
#     month_format = '%m'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['rubrics'] = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
#         return context


class BbRedirectView(RedirectView):
    url = '/detail/%(pk)d'


class BbDeleteView(DeleteView):
    model = Bb
    success_url = reverse_lazy('bboard:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)
        return context



@login_required(login_url='login')
def rubrics(request):
    rubs = Rubric.objects.annotate(cnt=Count('bb')).filter(cnt__gt=0)

    if request.method == 'POST':
        formset = RubricFormSet(request.POST)

        if formset.is_valid():

            formset.save(commit=False)

            for form in formset:
                if form.cleaned_data:
                    rubric = form.save(commit=False)
                    rubric.order = form.cleaned_data[ORDERING_FIELD_NAME]
                    rubric.save()

            for rubric in formset.deleted_objects:
                rubric.delete()

            # formset.save()
            return redirect('bboard:rubrics')
    else:
        formset = RubricFormSet()

    context = {'formset': formset, 'rubrics': rubs}
    return render(request, 'bboard/rubrics.html', context)


def search(request):
    if request.method == 'POST':
        sf = SearchForm(request.POST)
        if sf.is_valid():
            keyword = sf.cleaned_data['keyword']
            rubric_id = sf.cleaned_data['rubric'].pk
            # bbs = Bb.objects.filter(title__icontains=keyword,
            #                         rubric=rubric_id)
            bbs = Bb.objects.filter(title__iregex=keyword,
                                    rubric=rubric_id)

            context = {'bbs': bbs, 'form': sf}
            return render(request, 'bboard/search.html', context)
    else:
        sf = SearchForm()

templates/bboard/_create.html
{% extends "layout/basic.html" %}



{% block title %}Добавление объявления{% endblock %}

{% block content %}
<h2>Добавление объявления</h2>

    {% if form.is_multipart %}
        <form method="post" enctype="multipart/form-data">
    {% else %}
        <form method="post">
    {% endif %}
{#    <form action="{% url 'bboard:add_save' %}" method="post"> #}
        {% csrf_token %}
{#        {{ form.as_div }}#}
{#        {{ form.as_p }}#}
{#        <ul>#}
{#            {{ form.as_ul }}#}
{#        </ul>#}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Добавить</button>
        </form>
        </form>

{% endblock %}

templates/bboard/bb_confirm_delete.html
{% extends "layout/basic.html" %}


{% block title %}Удаление объявления{% endblock %}

{% block content %}
<h2>Удаление объявления</h2>
    <p>Рубрика: {{ bb.rubric.name }}</p>
    <h2>{{ bb.title }}</h2>
    <p>{{ bb.content }}</p>
    <p>Цена: {{ bb.price }} тг.</p>
    <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit">Удалить</button>
    </form>
{% endblock %}

templates/bboard/bb_detail.html
{% extends "layout/basic.html" %}

{% load thumbnail %}

{% block content %}
    <p>Рубрика: {{ bb.rubric.name }}</p>
    <h2>{{ bb.title }}</h2>

    {% if thumnail %}
        <p><img src="{{ bb.img|thumbnail_url:'default' }}" alt="bb.title"></p>
        <p><img src="{% thumbnail bb.img 'default' bw=True %}" alt="bb.title"></p>
    {% endif %}

    {% if bb.img %}
        <p><img src="{{ bb.img.url }}" alt="bb.title"></p>
    {% endif %}

{#    <p>{{ bb.content }}</p>#}
    <p>{{ bb.content.rendered }}</p>
{#    <p>Цена: {{ bb.price|default:'У товара нет цены'|floatformat:1 }} тг.</p>#}
    <p>Цена: {{ bb.price|default:'У товара нет цены' }} тг.</p>
    <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    <p>
        <a href="{% url 'bboard:update' bb.pk %}">Изменить</a> | 
        <a href="{% url 'bboard:delete' bb.pk %}">Удалить</a>
    </p>
    
    {% comment %}
    <pre>
{{ 'Python'|ljust:20 }}
{{ 'Python'|center:20 }}
{{ 'Python'|rjust:20 }}
    </pre>
    {% endcomment %}
    
{% endblock %}

templates/bboard/bb_form.html
{% extends "layout/basic.html" %}



{% block title %}Изменение объявления{% endblock %}

{% block content %}
<h2>Изменение объявления</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Изменить</button>
    </form>
{% endblock %}

templates/bboard/by_rubric.html
{% extends "layout/basic.html" %}


{% block title %}{{ current_rubric }}{% endblock %}

{% block content %}
    {% for bb in bbs %}
    <div>
        {% url 'bboard:detail' bb.pk as detail_url %}
        <h2>
{#            <a href="{% url 'bboard:detail' pk=bb.pk %}">{{ bb.title }}</a> #}
            {{ forloop.counter }}.
                <a href="{{ detail_url }}">{{ bb.title }}</a> ({{ bb.price }} тг.)
        </h2>
        <p>{{ bb.content.rendered }}</p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
        <p><a href="{{ detail_url }}">Подробнее</a></p>
    </div>
    {% empty %}
        <h2>Объявлений нет</h2>
    {% endfor %}
{% endblock %}

templates/bboard/create.html
{% extends "layout/basic.html" %}
{% load django_bootstrap5 %}


{% block title %}Добавление объявления{% endblock %}

{% block content %}
<h2>Добавление объявления</h2>

    {% if form.is_multipart %}
        <form method="post" enctype="multipart/form-data">
    {% else %}
        <form method="post">
    {% endif %}
        {% csrf_token %}
            {% bootstrap_form form layout='horizontal' show_help=False size='sm' %}
            {% bootstrap_button 'Добавить'%}
    
{% comment 'Теперь используем Django_bootstrap6' %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
    
        {% if form.non_field_errors %}
            <ul>
            {% for error in form.non_field_errors %}
                <li><em>{{ error|escape }}</em></li>
            {% endfor %}
            </ul>
        {% endif %}
        
        {% for field in form.visible_fields %}
            {% if field.errors %}
                <ul>
                {% for error in field.errors %}
                    <li><em>{{ error|escape }}</em></li>
                {% endfor %}
                </ul>
            {% endif %}
            
            <p>{{ field.label_tag }}<br>{{ field }}<br>
               {{ field.help_text }}</p>
        {% endfor %}
    
       {# <button type="submit" class="btn btn-primary">Добавить</button> #}
{% endcomment %}
        </form>
        </form>
{% endblock %}

templates/bboard/detail.html
{% extends "layout/basic.html" %}

{% block content %}
    <div>
        <h2>{{ bb.title_and_price }}</h2>
        <p>{{ bb.content }}</p>
        <p>
            <a href="{% url 'bboard:by_rubric' bb.rubric.pk %}">{{ bb.rubric.name }}</a>
        </p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
        <p><a href="{% url 'bboard:update' bb.pk %}">Изменить</a></p>
    </div>
{% endblock %}

templates/bboard/index.html
{% extends "layout/basic.html" %}
{% load bbcode_tags %}
{% load django_bootstrap5 %}
{% load bbtags %}



{% block content %}
        {% lst ',' '1' '2' '3' '4' '5' '6' %}
        {% ulist '1' '2' '3' '4' '5' '6' %}

{#    {{ block.super }}#}

    {% for bb in bbs %}
    <div class="{% cycle 'b1' 'b2' 'b3' %}">
        {% if forloop.first %}
            <h2 style="font-size: 36px;">
                <a href="{% url 'bboard:detail' pk=bb.pk %}">
                    {{ bb.title_and_price|upper }}</a>
            </h2>
        {% else %}
            <h2>
                <a href="{% url 'bboard:detail' pk=bb.pk %}">{{ bb.title_and_price }}</a>
            </h2>
        {% endif %}
        <p><strong>Цена:</strong> {{ bb.price|cur:'p.' }}</p>

            {# <p>{{ bb.content }}</p> #}
            {# <p>{{ bb.content|bbcode|safe }}</p> #}
            {# <p>{% bbcode bb.content %}</p> #}
            {# <p>{{ bb.content.rendered }}</p> #}


        {% ifchanged %}
            <p><a href="{% url 'bboard:by_rubric' bb.rubric.pk %}">
                {{ bb.rubric.name }}</a></p>
        {% endifchanged %}

        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
    </div>
    {% endfor %}

    <div>
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">&lt;</a>
            &nbsp; | &nbsp;
        {% endif %}

        Страница {{ page.number }} из {{ page.paginator.num_pages }}

        {% if page.has_next %}
            &nbsp; | &nbsp;
            <a href="?page={{ page.next_page_number }}">&gt;</a>
        {% endif %}
    </div>
{% comment 'Теперь используем Django_bootstrap6' %}
    {% if page.has_other_pages %}
        <nav aria-label="pagination">
            <ul class="pagination">

                {% if page.has_previous %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?page={{ page.previous_page_number }}">Назад</a>
                    </li>
                {% endif %}

                {% for p in page.paginator.page_range %}
                    {% if not p == page.number %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                        </li>
                    {% else %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link disabled bg-primary text-light"
                               href="?page={{ p }}">{{ p }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if page.has_next %}
                    <li class="page-item">
                        <a class="page-link"
                           href="?page={{ page.next_page_number }}">Вперёд</a>
                    </li>
                {% endif %}

            </ul>
        </nav>
    {% endif %}
{% endcomment %}
   {% bootstrap_pagination page size='sm' pages_to_show=5 %}


{% endblock %}

templates/bboard/rubrics.html
{% extends "layout/basic.html" %}
{% load django_bootstrap5 %}

{% block title %}Рубрики{% endblock %}

{% block content %}
<h2>Рубрики</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_alert '<p>Рубрика добавлена</p>' alert_type='success' dismissible=True %}
        {% bootstrap_formset formset layout='horizontal' %}
        {% bootstrap_button 'Очистить' Button_Type='reset' button_class='btn-secondary' %}
        {% bootstrap_button 'Сохранить' %}

{% comment 'Теперь используем Django_bootstrap6' %}
        {{ formset.management_form }}
        
        {% if formset.non_form_errors %}
            <ul>
            {% for error in formset.non_form_errors %}
                <li><em>{{ error|escape }}</em></li>
            {% endfor %}
            </ul>
        {% endif %}
    
        {% for form in formset %}
    
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
        
            {% if form.non_field_errors %}
                <ul>
                {% for error in form.non_field_errors %}
                    <li><em>{{ error|escape }}</em></li>
                {% endfor %}
                </ul>
            {% endif %}
            
            {% for field in form.visible_fields %}
                {% if field.errors %}
                    <ul>
                    {% for error in field.errors %}
                        <li><em>{{ error|escape }}</em></li>
                    {% endfor %}
                    </ul>
                {% endif %}
                
                <p>{{ field.label_tag }}<br>{{ field }}<br>
                   {{ field.help_text }}</p>
            {% endfor %}
        
        {% endfor %}
    
        <button type="submit" class="btn btn-primary">Сохранить</button>
{% endcomment %}
    </form>
{% endblock %}

templates/bboard/search.html
{% extends "layout/basic.html" %}



{% block title %}Поиск объявлений{% endblock %}

{% block content %}
<h2>Поиск объявлений</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Найти</button>
    </form>
    
    {% for bb in bbs %}
    <div>
        {% url 'bboard:detail' bb.pk as detail_url %}
        <h2>
            <a href="{{ detail_url }}">{{ bb.title }}</a> ({{ bb.price }} тг.)
        </h2>
        <p>{{ bb.content }}</p>
        <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
        <p><a href="{{ detail_url }}">Подробнее</a></p>
    </div>
    {% empty %}
        <h2>Объявлений нет</h2>
    {% endfor %}
    
{% endblock %}